---
title: "Prob 5, CP 2"
author: "Daniyel Rocha"
date: "29 de agosto de 2017"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openintro, quietly = T)
library(tidyverse, quietly = T)
#library(dplyr, quietly = T)
theme_set(theme_bw())
library(modelr, quietly = T)
library(broom, quietly = T)
library(GGally, quietly = T)
library(pscl, quietly = T)
library(modelr, quietly = T) # devtools::install_github("hadley/modelr")
```

Início

```{r}
speed_dating2 <- read.csv("https://raw.githubusercontent.com/nazareno/ciencia-de-dados-1/master/5-regressao/speed-dating/speed-dating2.csv") %>% na.omit()
```

```{r}
speed_dating2 <- speed_dating2 %>%
  mutate(dec = ifelse(dec == "yes", 1, 0))

dados_selecionados <- speed_dating2 %>%
  select(dec,attr,fun,intel,shar)
```

1. Dentre os fatores que você acha que podem ter efeito no match, quais fatores têm efeito significativo na chance de p1 decidir se encontrar novamente com p2? E como é esse efeito (positivo/negativo)?

```{r}
model <- glm(dec ~ attr + fun + intel + shar, 
         data = speed_dating2,
         family = "binomial")
tidy(model_attr_fun)
```


dec ~ attr + fun
